export const endpoints = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    refresh: '/api/v1/auth/refresh',
    me: '/api/v1/auth/me',
  },
  dashboard: {
    metrics: '/api/v1/dashboard/metrics',
    recentActivity: '/api/v1/dashboard/activity',
    marketplaceMetrics: '/api/v1/dashboard/marketplaces',
    riskTrend: '/api/v1/dashboard/risk-trend',
    systemHealth: '/api/v1/dashboard/system-health',
    fraudNodePreview: '/api/v1/dashboard/fraud-nodes',
    summary: '/api/v1/dashboard/summary',
    investigationTrend: '/api/v1/dashboard/investigation-trend',
    riskDistribution: '/api/v1/dashboard/risk-distribution',
    activeAlerts: '/api/v1/dashboard/active-alerts',
  },
  investigations: {
    list: '/api/v1/investigations',
    create: '/api/v1/investigations',
    details: (id: string) => `/api/v1/investigations/${id}`,
    delete: (id: string) => `/api/v1/investigations/${id}`,
    cancel: (id: string) => `/api/v1/investigations/${id}/cancel`,
    retry: (id: string) => `/api/v1/investigations/${id}/retry`,
    timeline: (id: string) => `/api/v1/investigations/${id}/timeline`,
    lineage: (id: string) => `/api/v1/investigations/${id}/lineage`,
    evidence: (id: string) => `/api/v1/investigations/${id}/evidence`,
    consensus: (id: string) => `/api/v1/investigations/${id}/consensus`,
    graph: (id: string) => `/api/v1/investigations/${id}/graph`,
    reasoning: (id: string) => `/api/v1/investigations/${id}/reasoning`,
    report: (id: string) => `/api/v1/investigations/${id}/report`,
  },
  alerts: {
    list: '/api/v1/alerts',
    details: (id: string) => `/api/v1/alerts/${id}`,
    acknowledge: (id: string) => `/api/v1/alerts/${id}/acknowledge`,
  },
  analytics: {
    dashboard: '/api/v1/analytics',
  },
  settings: {
    config: '/api/v1/settings',
    update: '/api/v1/settings',
  },
  graph: {
    data: '/api/v1/graph/data',
    stats: '/api/v1/graph/stats',
    nodeDetails: (id: string) => `/api/v1/graph/nodes/${id}`,
  },
  intelligence: {
    globalSummary: '/api/v1/intelligence/summary',
    knownSellers: '/api/v1/intelligence/sellers',
    fraudRings: '/api/v1/intelligence/rings',
    knownPatterns: '/api/v1/intelligence/patterns',
    repeatedImages: '/api/v1/intelligence/images',
    repeatedPhones: '/api/v1/intelligence/phones',
    repeatedInvoices: '/api/v1/intelligence/invoices',
    memoryInsights: '/api/v1/intelligence/memory',
  },
  discovery: {
    search: '/api/v1/discovery/search',
    marketplaces: '/api/v1/discovery/marketplaces',
    launch: '/api/v1/discovery/launch',
    batchStatus: (batchId: string) => `/api/v1/discovery/launch/${batchId}/status`,
    lineage: (candidateId: string) => `/api/v1/discovery/${candidateId}/lineage`,
    report: '/api/v1/discovery/report',
    batchReport: (batchId: string) => `/api/v1/discovery/batch/${batchId}/report`,
  },
  threatGraph: {
    full: '/api/v1/threat/graph',
    seller: (id: string) => `/api/v1/threat/seller/${id}`,
    product: (id: string) => `/api/v1/threat/product/${id}`,
    network: (id: string) => `/api/v1/threat/network/${id}`,
    related: (id: string) => `/api/v1/threat/related/${id}`,
  },
  memory: {
    similarInvestigations: '/api/v1/memory/similar-investigations',
    similarSellers: '/api/v1/memory/similar-sellers',
    similarProducts: '/api/v1/memory/similar-products',
    similarEvidence: '/api/v1/memory/similar-evidence',
  },
  scoring: {
    hierarchical: '/api/v1/scoring/hierarchical',
    explain: (id: string) => `/api/v1/scoring/explain/${id}`,
  },
  threatReports: {
    generate: '/api/v1/intelligence/reports/generate',
    get: (id: string) => `/api/v1/intelligence/reports/${id}`,
  },
  monitoring: {
    jobs: '/api/v1/monitor/jobs',
    history: '/api/v1/monitor/history',
    run: '/api/v1/monitor/run',
    pause: '/api/v1/monitor/pause',
    resume: '/api/v1/monitor/resume',
  },
  watchlists: {
    list: '/api/v1/watchlists',
    create: '/api/v1/watchlists',
    delete: (id: string) => `/api/v1/watchlists/${id}`,
    pause: (id: string) => `/api/v1/watchlists/${id}/pause`,
    resume: (id: string) => `/api/v1/watchlists/${id}/resume`,
    export: '/api/v1/watchlists/export',
  },
  recommendations: {
    prescriptive: '/api/v1/recommendations/prescriptive',
    execute: '/api/v1/recommendations/execute',
  },
  cases: {
    list: '/api/v1/cases',
    get: (id: string) => `/api/v1/cases/${id}`,
    updateStatus: (id: string) => `/api/v1/cases/${id}/status`,
    addComment: (id: string) => `/api/v1/cases/${id}/comments`,
    assign: (id: string) => `/api/v1/cases/${id}/assign`,
  },
  closedLoop: {
    trigger: '/api/v1/intelligence/closed-loop/trigger',
    telemetry: '/api/v1/intelligence/closed-loop/telemetry',
  },
  fraudRings: {
    list: '/api/v1/threat/rings',
    details: (id: string) => `/api/v1/threat/rings/${id}`,
    members: (id: string) => `/api/v1/threat/rings/${id}/members`,
    evidence: (id: string) => `/api/v1/threat/rings/${id}/evidence`,
  },
  providers: {
    health: '/api/v1/providers/health',
    rateLimits: '/api/v1/providers/rate-limits',
    parserMetrics: '/api/v1/providers/parser-metrics',
    parserInspector: '/api/v1/providers/parser-inspector',
    parserHistory: '/api/v1/providers/parser-history',
    runtimeMetrics: '/api/v1/providers/runtime-metrics',
    archive: '/api/v1/providers/archive',
    archiveItem: (id: string) => `/api/v1/providers/archive/${id}`,
    exportHealthReport: '/api/v1/providers/export/health-report',
  },
  export: {
    investigations: '/api/v1/investigations/export',
    watchlists: '/api/v1/watchlists/export',
    providerHealth: '/api/v1/providers/export/health-report',
  },
} as const;
