export const endpoints = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    refresh: '/api/v1/auth/refresh',
    me: '/api/v1/auth/me',
  },
  dashboard: {
    metrics: '/api/v1/dashboard/metrics',
    recentActivity: '/api/v1/dashboard/activity',
    marketplaceMetrics: '/api/v1/dashboard/marketplaces',
    riskTrend: '/api/v1/dashboard/risk-trend',
    systemHealth: '/api/v1/dashboard/system-health',
    fraudNodePreview: '/api/v1/dashboard/fraud-nodes',
    summary: '/api/v1/dashboard/summary',
    investigationTrend: '/api/v1/dashboard/investigation-trend',
    riskDistribution: '/api/v1/dashboard/risk-distribution',
    activeAlerts: '/api/v1/dashboard/active-alerts',
  },
  investigations: {
    list: '/api/v1/investigations',
    create: '/api/v1/investigations',
    details: (id: string) => `/api/v1/investigations/${id}`,
    delete: (id: string) => `/api/v1/investigations/${id}`,
    cancel: (id: string) => `/api/v1/investigations/${id}/cancel`,
    retry: (id: string) => `/api/v1/investigations/${id}/retry`,
    timeline: (id: string) => `/api/v1/investigations/${id}/timeline`,
    evidence: (id: string) => `/api/v1/investigations/${id}/evidence`,
    consensus: (id: string) => `/api/v1/investigations/${id}/consensus`,
    graph: (id: string) => `/api/v1/investigations/${id}/graph`,
    reasoning: (id: string) => `/api/v1/investigations/${id}/reasoning`,
    report: (id: string) => `/api/v1/investigations/${id}/report`,
  },
  alerts: {
    list: '/api/v1/alerts',
    details: (id: string) => `/api/v1/alerts/${id}`,
    acknowledge: (id: string) => `/api/v1/alerts/${id}/acknowledge`,
  },
  analytics: {
    dashboard: '/api/v1/analytics',
  },
  settings: {
    config: '/api/v1/settings',
    update: '/api/v1/settings',
  },
  graph: {
    data: '/api/v1/graph/data',
    stats: '/api/v1/graph/stats',
    nodeDetails: (id: string) => `/api/v1/graph/nodes/${id}`,
  },
  intelligence: {
    globalSummary: '/api/v1/intelligence/summary',
    knownSellers: '/api/v1/intelligence/sellers',
    fraudRings: '/api/v1/intelligence/rings',
    knownPatterns: '/api/v1/intelligence/patterns',
    repeatedImages: '/api/v1/intelligence/images',
    repeatedPhones: '/api/v1/intelligence/phones',
    repeatedInvoices: '/api/v1/intelligence/invoices',
    memoryInsights: '/api/v1/intelligence/memory',
  }
} as const;
