"""
Shared types and TypedDict models for CounterGuard backend.
"""

from typing import Any, Dict

from typing_extensions import TypedDict

JSONDict = Dict[str, Any]


class ListingData(TypedDict):
    """Data representing an e-commerce listing under investigation."""

    title: str
    marketplace: str
    url: str
    price: str
    seller: str
    location: str
    quantity_sold: int
    description: str


class EvidenceEvent(TypedDict):
    """An atomic event generated by an agent during an investigation timeline."""

    timestamp: str
    agent: str
    action: str
    detail: str
    confidence_delta: float


class AgentFinding(TypedDict):
    """Summary finding reported by a specific agent."""

    finding: str
    severity: str
