from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SourceCandidate(BaseModel):
    """
    Represents an unextracted product reference candidate source discovered by a SearchProvider.
    """

    title: str = Field(..., description="Candidate title or webpage heading")
    url: str = Field(..., description="Canonical target candidate URL")
    source_type: str = Field(
        "Other",
        description="Source classification: 'Official Store', 'Brand Store', 'Authorized Retailer', 'Marketplace', 'Other'",
    )
    provider: str = Field(
        ..., description="Name of the discovery provider that generated this candidate"
    )
    confidence: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Discovery confidence score between 0.0 and 1.0",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Extensible candidate metadata attributes"
    )


class DiscoveryResult(BaseModel):
    """
    Structured outcome generated by DiscoveryPipeline after normalization, execution, ranking, and verification.
    """

    query: str = Field(..., description="Original raw product search query")
    brand: str = Field(..., description="Identified brand hint")
    normalized_name: str = Field(
        ..., description="Canonical normalized query representation"
    )
    providers_used: List[str] = Field(
        default_factory=list, description="List of providers executed during discovery"
    )
    candidate_sources: List[SourceCandidate] = Field(
        default_factory=list, description="Ranked list of discovered candidate sources"
    )
    verified_source: Optional[SourceCandidate] = Field(
        None, description="Top candidate passing deterministic verification checks"
    )
    confidence: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Overall pipeline verification confidence score",
    )
    reasoning: str = Field(
        "", description="Human-readable explanation of ranking and verification outcome"
    )
    status: str = Field(
        "pending",
        description="Pipeline status: 'success', 'no_candidates_found', 'verification_failed'",
    )
    discovery_time_ms: float = Field(
        0.0, description="Total pipeline execution latency in milliseconds"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Extensible pipeline execution metadata"
    )
