import urllib.parse
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SourceCandidate(BaseModel):
    """
    Represents an unextracted product reference candidate source discovered by a SearchProvider.
    Includes rich analytics metadata for provider benchmarking and debugging.
    """

    title: str = Field(..., description="Candidate title or webpage heading")
    url: str = Field(..., description="Canonical target candidate URL")
    provider: str = Field(
        ..., description="Name of the discovery provider that generated this candidate"
    )
    domain: str = Field("", description="Extracted canonical domain hostname")
    source_type: str = Field(
        "Other",
        description="Source classification: 'Official Store', 'Brand Store', 'Authorized Retailer', 'Marketplace', 'Other'",
    )
    confidence: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Discovery confidence score between 0.0 and 1.0",
    )
    retrieval_method: str = Field(
        "http",
        description="Discovery method: 'static_catalog', 'http', 'serp_api', 'headless_browser'",
    )
    response_time_ms: float = Field(
        0.0, description="Provider query latency in milliseconds"
    )
    http_status: Optional[int] = Field(
        200, description="HTTP status code returned by provider or target"
    )
    crawl_depth: int = Field(0, description="Crawl depth level during discovery")
    language: str = Field("en", description="Detected or requested ISO language code")
    region: str = Field("US", description="ISO country or regional targeting code")
    timestamp: Optional[str] = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO UTC timestamp of candidate discovery",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Extensible candidate metadata attributes"
    )

    def model_post_init(self, __context: Any) -> None:
        """Automatically populates canonical domain if not explicitly provided."""
        if not self.domain and self.url:
            try:
                parsed = urllib.parse.urlparse(self.url.strip().lower())
                self.domain = (
                    parsed.hostname.replace("www.", "") if parsed.hostname else ""
                )
            except Exception:
                pass


class DiscoveryResult(BaseModel):
    """
    Structured outcome generated by DiscoveryPipeline after normalization, deduplication, ranking, and verification.
    """

    query: str = Field(..., description="Original raw product search query")
    brand: str = Field(..., description="Identified brand hint")
    normalized_name: str = Field(
        ..., description="Canonical normalized query representation"
    )
    providers_used: List[str] = Field(
        default_factory=list, description="List of providers executed during discovery"
    )
    candidate_sources: List[SourceCandidate] = Field(
        default_factory=list,
        description="Deduplicated and ranked list of candidate sources",
    )
    verified_source: Optional[SourceCandidate] = Field(
        None, description="Top candidate passing deterministic verification checks"
    )
    confidence: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Overall pipeline verification confidence score",
    )
    reasoning: str = Field(
        "", description="Human-readable explanation of ranking and verification outcome"
    )
    status: str = Field(
        "pending",
        description="Pipeline status: 'success', 'no_candidates_found', 'verification_failed'",
    )
    discovery_time_ms: float = Field(
        0.0, description="Total pipeline execution latency in milliseconds"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Extensible pipeline execution metadata"
    )
